### ISSUE TITLE
Not compatible with Tab Groups

### ISSUE THREAD

**Issue by maxsnet** [ZitRos/tab-slider#2]
Hello,

it messes up the tab groups.
cf [chrome://flags/#tab-groups](chrome://flags/#tab-groups)

though Tab Groups is still in experiments, I have read that it is going to be rolled over in next versions.

Best,

MPC

**Comment by nikitaeverywhere** [comment]
Yes!!! I knew someone will notice this! :D Thank you Max and thanks for using Tab Slider.

I tried tab groups right after their beta announcement, and found them to be a bit complicated, breaking the simplicity of tabs overall. My though was like "hey, this doesn't fit into the tab slider's concept". Personally, I have 3-4 pinned tabs and all other are "working tabs" - this worked perfectly well for me so far.

![image](https://user-images.githubusercontent.com/4989256/84390979-02caa080-ac01-11ea-8897-e5e216890178.png)

However, making Tab Slider compatible with tab groups is possible. **What would be your expectation of tabs behavior then?** What is your use case?

Anyway, I'd not implement it unless it is out for everyone (then, breaking tab groups will be considered a bug): personally, I see it as quite a complicated feature which might be dropped from Chrome one day (also the only browser supporing it).

Thanks! Hoping to hear your feedback soon.

**Comment by maxsnet** [comment]
Hi @ZitRos ! I have hundreds of open tabs so TabSlider is helping me to create tabs on the left so I can see them, and slide left any other tabs I am working on so I know that tabs on the left are what I am working on. I mainly use pinned tabs when I need manual sorting, for exemple when comparing prices. Sometimes I pin a few tabs that represent the 2-3 main subjects I am working on.

Using Tab Groups, Tab Slider could
1. slide left the whole group of the tab
2. slide left the tab within the group - this could be optional but useful when the group contains more tabs than the screen can show

Never break the tab/tab group relationship.

But the more I use Tab Groups and the less I find it well-thought:
- can't collapse groups
- can't slide left groups
- can't hide/restore groups
- groups don't appear in the Tab menu
- can't scroll tab strip

I have no idea how to access groups I can't see (even though I can send tabs there).
Should I buy a new screen?

![Screenshot 2020-06-11 at 16 28 02](https://user-images.githubusercontent.com/39408272/84398853-bb441480-ac00-11ea-8d56-f40e2a797026.png)

![Screenshot 2020-06-11 at 16 28 12](https://user-images.githubusercontent.com/39408272/84398852-baab7e00-ac00-11ea-8353-e9f6398246ae.png)

![Screenshot 2020-06-11 at 16 28 18](https://user-images.githubusercontent.com/39408272/84398851-baab7e00-ac00-11ea-84a2-d0bf3d14097b.png)

![Screenshot 2020-06-11 at 16 28 29](https://user-images.githubusercontent.com/39408272/84398848-b97a5100-ac00-11ea-8993-efd7acf89e4f.png)

Thank you for Tab Slider by the way, it is great !

Best,

Max

**Comment by nikitaeverywhere** [comment]
> Thank you for Tab Slider by the way, it is great !

Thank you!

Good to know, thanks for sharing your thoughts. Regarding buying a new screen - I do use a lot of tabs as well, but usually, at every moment I can decide to close all unnessesary tabs and immediatelly lower their number from 50+ to ~10. That's all I need for the context in my regular work. I don't close them just because I'm too lazy, which I guess the case for others as well.

I though of introducing one new feature: automatically closing old tabs when they're 50+ or so (or, depending on the screen size). Would it be useful for you?

**Comment by maxsnet** [comment]
I find it to be an interesting option as long as it is under control by the user.
For exemple an option to close the tabs
- hidden
- not loading (like a page uploading on Google Drive)
- not the result of a form
- not pinned
- opened for more than x days
+ be able to define a white list of sites that should never be closed automatically

Though I would not be a fan of it because of the inherent automatic loss of information: most of my open tabs have a piece of information I would like to retain, or, a group of open tabs shows me the state I was before switching to another activity. That is why for me tabs are important and my laziness is in not going through each of them but I want to _come back_ to them - hence the interest in tab groups. 

I am afraid that if I buy a new screen it will just increase the width of the tabs, instead of its numbers 😜

For me what is lacking in tab-related extensions is the goal to retain information: I am ok for you to close my tabs if you have made a PDF of it and uploaded it on my Google Drive, into a specific folder. Better if before I had the chance to add keywords, a theme or use the Tab Groups group name and that the PDF itself contains the URL too. Then another Chrome Extension searches into this folder when I search into Google.

A bit far-fetched for Tab Slider - more like [Sliders](https://en.wikipedia.org/wiki/Sliders) - but I am sure you get the point: it switches the mind from "I have too much tabs" to "the more tabs I have and the best 'personal Google database' I am creating". 

Wouldn't it be great ?

**Comment by maxsnet** [comment]
I am still using Tab Groups and it would be great if new tabs are created in the Tab Group. Is it something that could be added to Tab Slider ?

**Comment by nikitaeverywhere** [comment]
Saving tabs to PDFs (if I understood you correctly) sounds too weird for me to be honest :) That might be another extension, but definitely not the Tab Slider.

Well, we should expect tabs to be destructible, unless you have 32GB+ of RAM (which is not a guarantee of their persistense). Some old tabs get reloaded anyway if it exceeds RAM once you come back to them (it didn't happened on my 32GB Mac but on other laptops it's usual).

I am okay to fix the implementation for tab groups, here are my thoughts:

+ Tabs will slide the same way inside groups as globally (left = the most recent)
+ The entire tab group will slide left once one of its tab becomes active
+ Can you pin the tab group? I'd imagine the same behavior but in reversed order for pinned tab groups.
+ Can the tab group be empty? - will clarify

Does it sound good to you?

**Comment by maxsnet** [comment]
> Saving tabs to PDFs (if I understood you correctly) sounds too weird for me to be honest :) That might be another extension, but definitely not the Tab Slider.

I meant the content of the webpage of the tab(s), saved into a PDF. Or the document loaded by the tab, saved. But yes a totally different extension indeed !


> Well, we should expect tabs to be destructible, unless you have 32GB+ of RAM (which is not a guarantee of their persistense). Some old tabs get reloaded anyway if it exceeds RAM once you come back to them (it didn't happened on my 32GB Mac but on other laptops it's usual).

I use The Great Suspender, works flawlessly.


> I am okay to fix the implementation for tab groups, here are my thoughts:

Great!
 
> * Tabs will slide the same way inside groups as globally (right = the most recent)

👍

> * The entire tab group will slide left once one of its tab becomes active

👍

> * Can you pin the tab group? I'd imagine the same behavior but in reversed order for pinned tab groups.

I don't see how to pin tab groups, pinned tabs cannot be in a tab group and a pinned tab sent to a tab group is unpinned.

> * Can the tab group be empty? - will clarify

When the last tab of a group is closed, the group disappears.
 
> Does it sound good to you?

Yes! 👌


Another thing: Tab Slide creates new tabs on the left and slides left an active tab.
Because it loses the tab group / tab relationships, I would like Tab Slide not to slide tabs but to only creates tabs on the left. I thought putting 0 or negative second in the options could work, but did not (replaced by 0,1), so I put a huge number there. Even though it works, it is not an elegant solution.

Perhaps you would like to update your options to tick:
- create tabs on the left yes/no
- slide active tab left yes/no ( after x seconds)


Best,

Max

**Comment by maxsnet** [comment]
... and that a newly created tab is created in the group ...

**Comment by nikitaeverywhere** [comment]
Thanks for the info!

> I use The Great Suspender, works flawlessly.

Good to know. Though it's also not closing some tabs, e.g. "Detects tabs that contain forms with user input and can prevent them from suspending ...".




> Another thing: Tab Slide creates new tabs on the left and slides left an active tab.
> Because it loses the tab group / tab relationships, I would like Tab Slide not to slide tabs but to only creates tabs on the left. I thought putting 0 or negative second in the options could work, but did not (replaced by 0,1), so I put a huge number there. Even though it works, it is not an elegant solution.
> 
> Perhaps you would like to update your options to tick:
> 
> * create tabs on the left yes/no
> * slide active tab left yes/no ( after x seconds)

I have 2 thoughs: 

1. Create new tabs right after the current tab and immediately slide left to whatever position it fills with the above rules (so if it's in the tab group the new tab will stay in the tab group).
2. Always create tabs on the left regardless of tab group (the current behavior).

I'm more up to implementing `2`. Let me explain: CTRL+T should always be "let me start something new" behavior. E.g. I don't think where I want to open my tab (in which tab group), I just open it. Later, you can pin the newly created tab to any group. CTRL+T should not involve thinking or any prior actions and its result should always be expected.

**Comment by maxsnet** [comment]
Hi @ZitRos,

> > I use The Great Suspender, works flawlessly.
> 
> Good to know. Though it's also not closing some tabs, e.g. "Detects tabs that contain forms with user input and can prevent them from suspending ...".

It is not closing tabs but "suspending" them, and reloading them when accessing them.
Exemple of a suspended tab:

![Screenshot 2020-06-12 at 08 50 44](https://user-images.githubusercontent.com/39408272/84473732-dd35a980-ac89-11ea-81e3-a1e5500ad8a4.png)

Though it sill uses RAM, that is much less.

> I'm more up to implementing `2`. Let me explain: CTRL+T should always be "let me start something new" behavior. E.g. I don't think where I want to open my tab (in which tab group), I just open it. Later, you can pin the newly created tab to any group. CTRL+T should not involve thinking or any prior actions and its result should always be expected.

When I am focused on a topic, to switch topic is not _by default_. To stay in the flow - of the same topic - is, isn't it? As a result, most of my new tabs are created to continue working on the same topic. Therefore a tab created in a group should stay in the group, in my opinion.

For exemple, when I command-click a link, it creates a new tab in the same group. (This is the default behavior of Google Chrome).

But, when I command-T to create a new tab, the default behavior of Google Chrome is to create a new tab on the right of all tabs (out of the working group).

The default behaviors can be changed by [TabsPlus](https://chrome.google.com/webstore/detail/tabsplus/nikomkkhhpfoeamojhhgpfkpkdlfhfii) (not taking groups in consideration).

![Screenshot 2020-06-12 at 08 48 18](https://user-images.githubusercontent.com/39408272/84473526-84661100-ac89-11ea-93c2-847c599ac63a.png)

But TabPlus has one flaw: it doesn't make the distinction between tabs open by command-click and tabs opened by command-T, the choice could be made by the user:

- Position of tabs created by command-click (first of tabs, first of tab group, last of tab group, last of tabs, left of active tab (1), **right of active tab** (1) )
- Position of tabs created by command-T (first of tabs, first of tab group, last of tab group, last of tabs, left of active tab (1), **right of active tab** (1) )

_(1) If Active Tab is in a group, new tab is in the group._

Then, when the choice is to **keep tabs in the same group**, the tab slides left after x seconds defined by the user. If x is negative, **don't slide**.

When the choice is to slide out of groups, happens immediately.

In bold is my choice.

The default choice(s) could be the default behavior of Google Chrome, and if all of those choices are confusing for the user, it could be hidden under an "Advanced Parameters" link. And the Tab Groups options appear only when the #tab-groups flag is activated.

I am just throwing a lot of ideas at once and I know that each little idea can actually be very complicated to develop and implement. Tab Slider is very simple and very efficient ( = very well thought) and it should stay that way! ✊

Talking about development, is the development of a Chrome Extension following the MVC architecture? I am asking this because then things could be easier to schematise and implement/scale step by step, module per module.
 
Hope it helps.

Best,

MPC


PS:

> Saving tabs to PDFs (if I understood you correctly) sounds too weird for me to be honest :) That might be another extension, but definitely not the Tab Slider.

I had a thought about your comment and better would be to cache the content of the tab, like webcache.googleusercontent.com . Do you know if that is doable? (not Tab Slider related).

**Comment by nikitaeverywhere** [comment]
> It is not closing tabs but "suspending" them, and reloading them when accessing them.

But I guess it deletes f.e. the form data entered there.



> When I am focused on a topic, to switch topic is not _by default_. To stay in the flow - of the same topic - is, isn't it? As a result, most of my new tabs are created to continue working on the same topic. Therefore a tab created in a group should stay in the group, in my opinion.

But what would you do if you want to switch topic? This is a double-sided question, but for simplicity the default behavior (always opening new tabs on the left, regardless of the group). But this can be parametrized later based on your mention of how TabsPlus does this. Also, this is consistent with

> But, when I command-T to create a new tab, the default behavior of Google Chrome is to create a new tab on the right of all tabs (out of the working group).

you mention. I'll check whether the API gives the possiblity to track Ctrl+Click but I suspect it's not (or it requires the page access privilige).

> Talking about development, is the development of a Chrome Extension following the MVC architecture? I am asking this because then things could be easier to schematise and implement/scale step by step, module per module.

There's no place for "V" component for extensions, if not talking about UIs or "settings" page. Besides it is just the javascript-based web application. Also, browser's APIs are quite limited to do many seemingly possible things. For instance, I'd love to implement this in Tab Slider: when the user Ctrl+Tab but **doesn't release the CTRL button**, the tab won't slide up until they release CTRL. This would be amazing (as sometimes I don't want to trigger the tab to slide and just watch the page for a couple of seconds). But it's simply not possible because of browser's API limitations.

> I had a thought about your comment and better would be to cache the content of the tab, like webcache.googleusercontent.com . Do you know if that is doable? (not Tab Slider related).

I think it's not. Again, because of the API. The behaviour of "dumping" and restoring tabs should be implemented in the browser itself though.

**Comment by nikitaeverywhere** [comment]
Hi @maxsnet! Now I noticed tab groups in Chrome (stable release channel) and made it, thanks for using Tab Slider! 

![TNxxIlGUHK](https://user-images.githubusercontent.com/4989256/97109943-ec6c3f80-16de-11eb-8565-0257eaf1b233.gif)

However, it may take some time to:

+ TabSlider 1.9 to be published in Chrome Store
+ Chrome 88 to be shipped in a stable Chrome release channel. It's funny that tabs are supported since Chrome 85 or so, but are not supported by [Chrome tabs API](https://developer.chrome.com/extensions/tabs) up until Chrome 88. Currently, only Chrome for devs support this API.

Bonus: I also added "max tabs" setting. It's potentially destructive, so the default limit is 999 tabs. But you can adjust it in settings.
